export interface ArtifactListItem {
  id: string;
  filename: string;
  content: string;
  createdAt: Date;
  agent: { name: string; role: string } | null;
}

/**
 * Deliverables generated by the generate_text_file tool
 * (lib/ai/tools/generate-file.ts). Presentational only, mirroring
 * ActivityFeed's shape — the page fetches, this renders. The download
 * link is a plain `data:` URI rather than a new API route: this is a
 * Server Component tree that already has the content in hand, so there's
 * nothing a route would add.
 */
export function ArtifactList({
  artifacts,
}: {
  artifacts: readonly ArtifactListItem[];
}) {
  if (artifacts.length === 0) {
    return (
      <p
        className="rounded-lg border border-dashed border-border p-4 text-sm text-muted"
        data-testid="no-artifacts"
      >
        No files generated yet.
      </p>
    );
  }

  return (
    <div
      className="space-y-3 rounded-lg border border-border bg-surface p-4"
      data-testid="artifact-list"
    >
      <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">
        Deliverables
      </h2>
      <ul className="space-y-2">
        {artifacts.map((artifact) => (
          <li
            key={artifact.id}
            className="flex items-center justify-between gap-3 border-b border-border pb-2 text-sm last:border-b-0 last:pb-0"
          >
            <div className="min-w-0">
              <p className="truncate text-ink">{artifact.filename}</p>
              {artifact.agent ? (
                <p className="text-xs text-muted">
                  {artifact.agent.name} ·{" "}
                  {artifact.createdAt.toLocaleTimeString()}
                </p>
              ) : null}
            </div>
            <a
              download={artifact.filename}
              href={`data:text/plain;charset=utf-8,${encodeURIComponent(artifact.content)}`}
              className="shrink-0 text-xs text-accent hover:underline"
            >
              Download
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
